-- Existing runtime-owned tables: apply only columns absent in DESCRIBE.
-- Owning initializers perform these upgrades idempotently during startup.
ALTER TABLE NOVA_SYSTEM.CONFIG_AGENTS ADD COLUMN release_manifest_id VARCHAR(64);
ALTER TABLE NOVA_SYSTEM.AUDIT_SEMANTIC_QUERY_USAGE ADD COLUMN active_role VARCHAR(128);
ALTER TABLE NOVA_SYSTEM.AUDIT_SEMANTIC_QUERY_USAGE ADD COLUMN security_context_version BIGINT;
ALTER TABLE NOVA_SYSTEM.AUDIT_SEMANTIC_QUERY_USAGE ADD COLUMN semantic_version BIGINT;
ALTER TABLE NOVA_SYSTEM.CONFIG_AGENT_RUNS ADD COLUMN session_id VARCHAR(64);
ALTER TABLE NOVA_SYSTEM.CONFIG_AGENT_RUNS ADD COLUMN security_version INT;
