-- Additive migration for existing NOVA_SYSTEM.CONFIG_AI_MODELS installations.
-- New installations receive these columns from docker/init-nova.sql.
ALTER TABLE NOVA_SYSTEM.CONFIG_AI_MODELS ADD COLUMN logical_alias VARCHAR(128);
ALTER TABLE NOVA_SYSTEM.CONFIG_AI_MODELS ADD COLUMN revision VARCHAR(128);
ALTER TABLE NOVA_SYSTEM.CONFIG_AI_MODELS ADD COLUMN dimensions INT;
ALTER TABLE NOVA_SYSTEM.CONFIG_AI_MODELS ADD COLUMN modality VARCHAR(32);
ALTER TABLE NOVA_SYSTEM.CONFIG_AI_MODELS ADD COLUMN metric VARCHAR(32);
