"""Generated StarRocks 4.1.4 ANTLR4 parser (Python3 target).

The vendored grammar is pinned to the commit the `4.1.4` images are built from
(`4a9848edf03f5c936dac664b2d52527f48e72eb0`, NOVA-51).

These modules are generated by ``backend/scripts/generate_grammar.sh`` from the
vendored, NOVA-marked grammar in this directory. **Do not edit them by hand** --
edit the ``.g4`` sources and regenerate, then commit both together
(``backend/scripts/check_grammar_drift.py`` enforces this in CI).

``java`` is a build-time dependency only; at runtime only
``antlr4-python3-runtime`` is needed.

ANTLR's ``.interp`` ATN-serialization files are deliberately not committed: the
parser embeds its serialized ATN in ``serializedATN()`` and never reads them, so
they are ~530 KB of tooling-only churn on each regeneration.
"""

from __future__ import annotations

from .StarRocksLexer import StarRocksLexer
from .StarRocksParser import StarRocksParser
from .StarRocksVisitor import StarRocksVisitor

__all__ = ["StarRocksLexer", "StarRocksParser", "StarRocksVisitor"]
