#!/usr/bin/env python3
"""Write prometheus.split.yml: the base scrape config with DNS discovery.

A split deployment scales the web, query and proxy tiers, so their targets
cannot be listed in a file. This derives the split config from prometheus.yml
by replacing those three jobs' file discovery with Docker DNS lookups, which
return one address per replica. Everything else is copied unchanged.

    python docker/observability/build_prometheus_split.py
"""

from __future__ import annotations

import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
BASE = HERE / "prometheus" / "prometheus.yml"
SPLIT = HERE / "prometheus" / "prometheus.split.yml"

#: job name -> (Docker service name, metrics port)
DISCOVERED = {
    "nova-backend": ("nova-backend", 8000),
    "nova-query": ("nova-query", 8000),
    "nova-proxy": ("nova-proxy", 9104),
}
HEADER = "# Generated by build_prometheus_split.py from prometheus.yml. Do not edit.\n"


def render(base: str) -> str:
    text = base
    for job, (service, port) in DISCOVERED.items():
        pattern = re.compile(
            rf"(  - job_name: {re.escape(job)}\n(?:    .*\n)*?)"
            r"    file_sd_configs:\n      - files: \[[^\]]+\]\n"
        )
        replacement = (
            r"\1"
            "    dns_sd_configs:\n"
            f'      - names: ["{service}"]\n'
            "        type: A\n"
            f"        port: {port}\n"
            "        refresh_interval: 15s\n"
        )
        text, count = pattern.subn(replacement, text)
        if count != 1:
            raise SystemExit(f"prometheus.yml has no file-discovered job named {job}")
    return HEADER + text


def main() -> None:
    SPLIT.write_text(render(BASE.read_text()))
    print(f"{SPLIT.relative_to(HERE.parent)}: {len(DISCOVERED)} jobs use DNS discovery")


if __name__ == "__main__":
    main()
