/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedQueryHistoryRouteImport } from './routes/_authenticated/query-history'
import { Route as AuthenticatedActiveQueryRouteImport } from './routes/_authenticated/active-query'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedMonitoringRouteRouteImport } from './routes/_authenticated/monitoring/route'
import { Route as AuthenticatedWorkspacesIndexRouteImport } from './routes/_authenticated/workspaces/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedMonitoringIndexRouteImport } from './routes/_authenticated/monitoring/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedMonitoringTasksRouteImport } from './routes/_authenticated/monitoring/tasks'
import { Route as AuthenticatedMonitoringLoadsRouteImport } from './routes/_authenticated/monitoring/loads'
import { Route as AuthenticatedMonitoringCostRouteImport } from './routes/_authenticated/monitoring/cost'
import { Route as AuthenticatedMonitoringAuditRouteImport } from './routes/_authenticated/monitoring/audit'
import { Route as AuthenticatedMonitoringActiveRouteImport } from './routes/_authenticated/monitoring/active'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueryHistoryRoute =
  AuthenticatedQueryHistoryRouteImport.update({
    id: '/query-history',
    path: '/query-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActiveQueryRoute =
  AuthenticatedActiveQueryRouteImport.update({
    id: '/active-query',
    path: '/active-query',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedMonitoringRouteRoute =
  AuthenticatedMonitoringRouteRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspacesIndexRoute =
  AuthenticatedWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonitoringIndexRoute =
  AuthenticatedMonitoringIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMonitoringRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedMonitoringTasksRoute =
  AuthenticatedMonitoringTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedMonitoringRouteRoute,
  } as any)
const AuthenticatedMonitoringLoadsRoute =
  AuthenticatedMonitoringLoadsRouteImport.update({
    id: '/loads',
    path: '/loads',
    getParentRoute: () => AuthenticatedMonitoringRouteRoute,
  } as any)
const AuthenticatedMonitoringCostRoute =
  AuthenticatedMonitoringCostRouteImport.update({
    id: '/cost',
    path: '/cost',
    getParentRoute: () => AuthenticatedMonitoringRouteRoute,
  } as any)
const AuthenticatedMonitoringAuditRoute =
  AuthenticatedMonitoringAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedMonitoringRouteRoute,
  } as any)
const AuthenticatedMonitoringActiveRoute =
  AuthenticatedMonitoringActiveRouteImport.update({
    id: '/active',
    path: '/active',
    getParentRoute: () => AuthenticatedMonitoringRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/monitoring': typeof AuthenticatedMonitoringRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/active-query': typeof AuthenticatedActiveQueryRoute
  '/query-history': typeof AuthenticatedQueryHistoryRoute
  '/monitoring/active': typeof AuthenticatedMonitoringActiveRoute
  '/monitoring/audit': typeof AuthenticatedMonitoringAuditRoute
  '/monitoring/cost': typeof AuthenticatedMonitoringCostRoute
  '/monitoring/loads': typeof AuthenticatedMonitoringLoadsRoute
  '/monitoring/tasks': typeof AuthenticatedMonitoringTasksRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/monitoring/': typeof AuthenticatedMonitoringIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/active-query': typeof AuthenticatedActiveQueryRoute
  '/query-history': typeof AuthenticatedQueryHistoryRoute
  '/': typeof AuthenticatedIndexRoute
  '/monitoring/active': typeof AuthenticatedMonitoringActiveRoute
  '/monitoring/audit': typeof AuthenticatedMonitoringAuditRoute
  '/monitoring/cost': typeof AuthenticatedMonitoringCostRoute
  '/monitoring/loads': typeof AuthenticatedMonitoringLoadsRoute
  '/monitoring/tasks': typeof AuthenticatedMonitoringTasksRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/monitoring': typeof AuthenticatedMonitoringIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/active-query': typeof AuthenticatedActiveQueryRoute
  '/_authenticated/query-history': typeof AuthenticatedQueryHistoryRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/monitoring/active': typeof AuthenticatedMonitoringActiveRoute
  '/_authenticated/monitoring/audit': typeof AuthenticatedMonitoringAuditRoute
  '/_authenticated/monitoring/cost': typeof AuthenticatedMonitoringCostRoute
  '/_authenticated/monitoring/loads': typeof AuthenticatedMonitoringLoadsRoute
  '/_authenticated/monitoring/tasks': typeof AuthenticatedMonitoringTasksRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/monitoring/': typeof AuthenticatedMonitoringIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/monitoring'
    | '/sign-in'
    | '/active-query'
    | '/query-history'
    | '/monitoring/active'
    | '/monitoring/audit'
    | '/monitoring/cost'
    | '/monitoring/loads'
    | '/monitoring/tasks'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps/'
    | '/chats/'
    | '/monitoring/'
    | '/tasks/'
    | '/users/'
    | '/workspaces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/sign-in'
    | '/active-query'
    | '/query-history'
    | '/'
    | '/monitoring/active'
    | '/monitoring/audit'
    | '/monitoring/cost'
    | '/monitoring/loads'
    | '/monitoring/tasks'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/monitoring'
    | '/tasks'
    | '/users'
    | '/workspaces'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/monitoring'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/sign-in'
    | '/_authenticated/active-query'
    | '/_authenticated/query-history'
    | '/_authenticated/'
    | '/_authenticated/monitoring/active'
    | '/_authenticated/monitoring/audit'
    | '/_authenticated/monitoring/cost'
    | '/_authenticated/monitoring/loads'
    | '/_authenticated/monitoring/tasks'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/monitoring/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/workspaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/query-history': {
      id: '/_authenticated/query-history'
      path: '/query-history'
      fullPath: '/query-history'
      preLoaderRoute: typeof AuthenticatedQueryHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/active-query': {
      id: '/_authenticated/active-query'
      path: '/active-query'
      fullPath: '/active-query'
      preLoaderRoute: typeof AuthenticatedActiveQueryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthenticatedWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring/': {
      id: '/_authenticated/monitoring/'
      path: '/'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof AuthenticatedMonitoringIndexRouteImport
      parentRoute: typeof AuthenticatedMonitoringRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/monitoring/tasks': {
      id: '/_authenticated/monitoring/tasks'
      path: '/tasks'
      fullPath: '/monitoring/tasks'
      preLoaderRoute: typeof AuthenticatedMonitoringTasksRouteImport
      parentRoute: typeof AuthenticatedMonitoringRouteRoute
    }
    '/_authenticated/monitoring/loads': {
      id: '/_authenticated/monitoring/loads'
      path: '/loads'
      fullPath: '/monitoring/loads'
      preLoaderRoute: typeof AuthenticatedMonitoringLoadsRouteImport
      parentRoute: typeof AuthenticatedMonitoringRouteRoute
    }
    '/_authenticated/monitoring/cost': {
      id: '/_authenticated/monitoring/cost'
      path: '/cost'
      fullPath: '/monitoring/cost'
      preLoaderRoute: typeof AuthenticatedMonitoringCostRouteImport
      parentRoute: typeof AuthenticatedMonitoringRouteRoute
    }
    '/_authenticated/monitoring/audit': {
      id: '/_authenticated/monitoring/audit'
      path: '/audit'
      fullPath: '/monitoring/audit'
      preLoaderRoute: typeof AuthenticatedMonitoringAuditRouteImport
      parentRoute: typeof AuthenticatedMonitoringRouteRoute
    }
    '/_authenticated/monitoring/active': {
      id: '/_authenticated/monitoring/active'
      path: '/active'
      fullPath: '/monitoring/active'
      preLoaderRoute: typeof AuthenticatedMonitoringActiveRouteImport
      parentRoute: typeof AuthenticatedMonitoringRouteRoute
    }
  }
}

interface AuthenticatedMonitoringRouteRouteChildren {
  AuthenticatedMonitoringActiveRoute: typeof AuthenticatedMonitoringActiveRoute
  AuthenticatedMonitoringAuditRoute: typeof AuthenticatedMonitoringAuditRoute
  AuthenticatedMonitoringCostRoute: typeof AuthenticatedMonitoringCostRoute
  AuthenticatedMonitoringLoadsRoute: typeof AuthenticatedMonitoringLoadsRoute
  AuthenticatedMonitoringTasksRoute: typeof AuthenticatedMonitoringTasksRoute
  AuthenticatedMonitoringIndexRoute: typeof AuthenticatedMonitoringIndexRoute
}

const AuthenticatedMonitoringRouteRouteChildren: AuthenticatedMonitoringRouteRouteChildren =
  {
    AuthenticatedMonitoringActiveRoute: AuthenticatedMonitoringActiveRoute,
    AuthenticatedMonitoringAuditRoute: AuthenticatedMonitoringAuditRoute,
    AuthenticatedMonitoringCostRoute: AuthenticatedMonitoringCostRoute,
    AuthenticatedMonitoringLoadsRoute: AuthenticatedMonitoringLoadsRoute,
    AuthenticatedMonitoringTasksRoute: AuthenticatedMonitoringTasksRoute,
    AuthenticatedMonitoringIndexRoute: AuthenticatedMonitoringIndexRoute,
  }

const AuthenticatedMonitoringRouteRouteWithChildren =
  AuthenticatedMonitoringRouteRoute._addFileChildren(
    AuthenticatedMonitoringRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMonitoringRouteRoute: typeof AuthenticatedMonitoringRouteRouteWithChildren
  AuthenticatedActiveQueryRoute: typeof AuthenticatedActiveQueryRoute
  AuthenticatedQueryHistoryRoute: typeof AuthenticatedQueryHistoryRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWorkspacesIndexRoute: typeof AuthenticatedWorkspacesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMonitoringRouteRoute:
    AuthenticatedMonitoringRouteRouteWithChildren,
  AuthenticatedActiveQueryRoute: AuthenticatedActiveQueryRoute,
  AuthenticatedQueryHistoryRoute: AuthenticatedQueryHistoryRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWorkspacesIndexRoute: AuthenticatedWorkspacesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
