/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedActiveQueryRouteImport } from './routes/_authenticated/active-query'
import { Route as AuthenticatedDatabaseExplorerRouteImport } from './routes/_authenticated/database-explorer'
import { Route as AuthenticatedMigrationRouteImport } from './routes/_authenticated/migration'
import { Route as AuthenticatedMonitoringRouteRouteImport } from './routes/_authenticated/monitoring/route'
import { Route as AuthenticatedQueryCostRouteImport } from './routes/_authenticated/query-cost'
import { Route as AuthenticatedQueryHistoryRouteImport } from './routes/_authenticated/query-history'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated/agents/index'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated/agents/$agentId'
import { Route as AuthenticatedAgentsSkillsRouteImport } from './routes/_authenticated/agents/skills'
import { Route as AuthenticatedAgentsStudioRouteImport } from './routes/_authenticated/agents/studio'
import { Route as AuthenticatedAgentsToolsRouteImport } from './routes/_authenticated/agents/tools'
import { Route as AuthenticatedAiProvidersIndexRouteImport } from './routes/_authenticated/ai-providers/index'
import { Route as AuthenticatedExternalCatalogsIndexRouteImport } from './routes/_authenticated/external-catalogs/index'
import { Route as AuthenticatedFunctionsIndexRouteImport } from './routes/_authenticated/functions/index'
import { Route as AuthenticatedMlModelsIndexRouteImport } from './routes/_authenticated/ml-models/index'
import { Route as AuthenticatedMonitoringIndexRouteImport } from './routes/_authenticated/monitoring/index'
import { Route as AuthenticatedMonitoringActiveRouteImport } from './routes/_authenticated/monitoring/active'
import { Route as AuthenticatedMonitoringAuditRouteImport } from './routes/_authenticated/monitoring/audit'
import { Route as AuthenticatedMonitoringClusterRouteImport } from './routes/_authenticated/monitoring/cluster'
import { Route as AuthenticatedMonitoringHealthRouteImport } from './routes/_authenticated/monitoring/health'
import { Route as AuthenticatedMonitoringLoadsRouteImport } from './routes/_authenticated/monitoring/loads'
import { Route as AuthenticatedMonitoringTasksRouteImport } from './routes/_authenticated/monitoring/tasks'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedRolesNameRouteImport } from './routes/_authenticated/roles/$name'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedStagesIndexRouteImport } from './routes/_authenticated/stages/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedTasksGraphIdRouteImport } from './routes/_authenticated/tasks/$graphId'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedUsersUsernameRouteImport } from './routes/_authenticated/users/$username'
import { Route as AuthenticatedWorkspacesIndexRouteImport } from './routes/_authenticated/workspaces/index'
import { Route as AuthenticatedAgentsSemanticIndexRouteImport } from './routes/_authenticated/agents/semantic/index'
import { Route as AuthenticatedAgentsSemanticBuilderRouteImport } from './routes/_authenticated/agents/semantic/builder'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActiveQueryRoute =
  AuthenticatedActiveQueryRouteImport.update({
    id: '/active-query',
    path: '/active-query',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatabaseExplorerRoute =
  AuthenticatedDatabaseExplorerRouteImport.update({
    id: '/database-explorer',
    path: '/database-explorer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMigrationRoute = AuthenticatedMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonitoringRouteRoute =
  AuthenticatedMonitoringRouteRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQueryCostRoute = AuthenticatedQueryCostRouteImport.update({
  id: '/query-cost',
  path: '/query-cost',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueryHistoryRoute =
  AuthenticatedQueryHistoryRouteImport.update({
    id: '/query-history',
    path: '/query-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsAgentIdRoute =
  AuthenticatedAgentsAgentIdRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsSkillsRoute =
  AuthenticatedAgentsSkillsRouteImport.update({
    id: '/agents/skills',
    path: '/agents/skills',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsStudioRoute =
  AuthenticatedAgentsStudioRouteImport.update({
    id: '/agents/studio',
    path: '/agents/studio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsToolsRoute =
  AuthenticatedAgentsToolsRouteImport.update({
    id: '/agents/tools',
    path: '/agents/tools',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiProvidersIndexRoute =
  AuthenticatedAiProvidersIndexRouteImport.update({
    id: '/ai-providers/',
    path: '/ai-providers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExternalCatalogsIndexRoute =
  AuthenticatedExternalCatalogsIndexRouteImport.update({
    id: '/external-catalogs/',
    path: '/external-catalogs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFunctionsIndexRoute =
  AuthenticatedFunctionsIndexRouteImport.update({
    id: '/functions/',
    path: '/functions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMlModelsIndexRoute =
  AuthenticatedMlModelsIndexRouteImport.update({
    id: '/ml-models/',
    path: '/ml-models/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitoringIndexRoute =
  AuthenticatedMonitoringIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMonitoringRouteRoute,
  } as any)
const AuthenticatedMonitoringActiveRoute =
  AuthenticatedMonitoringActiveRouteImport.update({
    id: '/active',
    path: '/active',
    getParentRoute: () => AuthenticatedMonitoringRouteRoute,
  } as any)
const AuthenticatedMonitoringAuditRoute =
  AuthenticatedMonitoringAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedMonitoringRouteRoute,
  } as any)
const AuthenticatedMonitoringClusterRoute =
  AuthenticatedMonitoringClusterRouteImport.update({
    id: '/cluster',
    path: '/cluster',
    getParentRoute: () => AuthenticatedMonitoringRouteRoute,
  } as any)
const AuthenticatedMonitoringHealthRoute =
  AuthenticatedMonitoringHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedMonitoringRouteRoute,
  } as any)
const AuthenticatedMonitoringLoadsRoute =
  AuthenticatedMonitoringLoadsRouteImport.update({
    id: '/loads',
    path: '/loads',
    getParentRoute: () => AuthenticatedMonitoringRouteRoute,
  } as any)
const AuthenticatedMonitoringTasksRoute =
  AuthenticatedMonitoringTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedMonitoringRouteRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesNameRoute = AuthenticatedRolesNameRouteImport.update({
  id: '/roles/$name',
  path: '/roles/$name',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStagesIndexRoute =
  AuthenticatedStagesIndexRouteImport.update({
    id: '/stages/',
    path: '/stages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksGraphIdRoute =
  AuthenticatedTasksGraphIdRouteImport.update({
    id: '/tasks/$graphId',
    path: '/tasks/$graphId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersUsernameRoute =
  AuthenticatedUsersUsernameRouteImport.update({
    id: '/users/$username',
    path: '/users/$username',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspacesIndexRoute =
  AuthenticatedWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsSemanticIndexRoute =
  AuthenticatedAgentsSemanticIndexRouteImport.update({
    id: '/agents/semantic/',
    path: '/agents/semantic/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsSemanticBuilderRoute =
  AuthenticatedAgentsSemanticBuilderRouteImport.update({
    id: '/agents/semantic/builder',
    path: '/agents/semantic/builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/studio': typeof StudioRoute
  '/monitoring': typeof AuthenticatedMonitoringRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/active-query': typeof AuthenticatedActiveQueryRoute
  '/database-explorer': typeof AuthenticatedDatabaseExplorerRoute
  '/migration': typeof AuthenticatedMigrationRoute
  '/query-cost': typeof AuthenticatedQueryCostRoute
  '/query-history': typeof AuthenticatedQueryHistoryRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/agents/skills': typeof AuthenticatedAgentsSkillsRoute
  '/agents/studio': typeof AuthenticatedAgentsStudioRoute
  '/agents/tools': typeof AuthenticatedAgentsToolsRoute
  '/monitoring/active': typeof AuthenticatedMonitoringActiveRoute
  '/monitoring/audit': typeof AuthenticatedMonitoringAuditRoute
  '/monitoring/cluster': typeof AuthenticatedMonitoringClusterRoute
  '/monitoring/health': typeof AuthenticatedMonitoringHealthRoute
  '/monitoring/loads': typeof AuthenticatedMonitoringLoadsRoute
  '/monitoring/tasks': typeof AuthenticatedMonitoringTasksRoute
  '/roles/$name': typeof AuthenticatedRolesNameRoute
  '/tasks/$graphId': typeof AuthenticatedTasksGraphIdRoute
  '/users/$username': typeof AuthenticatedUsersUsernameRoute
  '/agents/': typeof AuthenticatedAgentsIndexRoute
  '/ai-providers/': typeof AuthenticatedAiProvidersIndexRoute
  '/external-catalogs/': typeof AuthenticatedExternalCatalogsIndexRoute
  '/functions/': typeof AuthenticatedFunctionsIndexRoute
  '/ml-models/': typeof AuthenticatedMlModelsIndexRoute
  '/monitoring/': typeof AuthenticatedMonitoringIndexRoute
  '/roles/': typeof AuthenticatedRolesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/stages/': typeof AuthenticatedStagesIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/agents/semantic/builder': typeof AuthenticatedAgentsSemanticBuilderRoute
  '/agents/semantic/': typeof AuthenticatedAgentsSemanticIndexRoute
}
export interface FileRoutesByTo {
  '/studio': typeof StudioRoute
  '/sign-in': typeof authSignInRoute
  '/active-query': typeof AuthenticatedActiveQueryRoute
  '/database-explorer': typeof AuthenticatedDatabaseExplorerRoute
  '/migration': typeof AuthenticatedMigrationRoute
  '/query-cost': typeof AuthenticatedQueryCostRoute
  '/query-history': typeof AuthenticatedQueryHistoryRoute
  '/': typeof AuthenticatedIndexRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/agents/skills': typeof AuthenticatedAgentsSkillsRoute
  '/agents/studio': typeof AuthenticatedAgentsStudioRoute
  '/agents/tools': typeof AuthenticatedAgentsToolsRoute
  '/monitoring/active': typeof AuthenticatedMonitoringActiveRoute
  '/monitoring/audit': typeof AuthenticatedMonitoringAuditRoute
  '/monitoring/cluster': typeof AuthenticatedMonitoringClusterRoute
  '/monitoring/health': typeof AuthenticatedMonitoringHealthRoute
  '/monitoring/loads': typeof AuthenticatedMonitoringLoadsRoute
  '/monitoring/tasks': typeof AuthenticatedMonitoringTasksRoute
  '/roles/$name': typeof AuthenticatedRolesNameRoute
  '/tasks/$graphId': typeof AuthenticatedTasksGraphIdRoute
  '/users/$username': typeof AuthenticatedUsersUsernameRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/ai-providers': typeof AuthenticatedAiProvidersIndexRoute
  '/external-catalogs': typeof AuthenticatedExternalCatalogsIndexRoute
  '/functions': typeof AuthenticatedFunctionsIndexRoute
  '/ml-models': typeof AuthenticatedMlModelsIndexRoute
  '/monitoring': typeof AuthenticatedMonitoringIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/stages': typeof AuthenticatedStagesIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/agents/semantic/builder': typeof AuthenticatedAgentsSemanticBuilderRoute
  '/agents/semantic': typeof AuthenticatedAgentsSemanticIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/studio': typeof StudioRoute
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/active-query': typeof AuthenticatedActiveQueryRoute
  '/_authenticated/database-explorer': typeof AuthenticatedDatabaseExplorerRoute
  '/_authenticated/migration': typeof AuthenticatedMigrationRoute
  '/_authenticated/query-cost': typeof AuthenticatedQueryCostRoute
  '/_authenticated/query-history': typeof AuthenticatedQueryHistoryRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/_authenticated/agents/skills': typeof AuthenticatedAgentsSkillsRoute
  '/_authenticated/agents/studio': typeof AuthenticatedAgentsStudioRoute
  '/_authenticated/agents/tools': typeof AuthenticatedAgentsToolsRoute
  '/_authenticated/monitoring/active': typeof AuthenticatedMonitoringActiveRoute
  '/_authenticated/monitoring/audit': typeof AuthenticatedMonitoringAuditRoute
  '/_authenticated/monitoring/cluster': typeof AuthenticatedMonitoringClusterRoute
  '/_authenticated/monitoring/health': typeof AuthenticatedMonitoringHealthRoute
  '/_authenticated/monitoring/loads': typeof AuthenticatedMonitoringLoadsRoute
  '/_authenticated/monitoring/tasks': typeof AuthenticatedMonitoringTasksRoute
  '/_authenticated/roles/$name': typeof AuthenticatedRolesNameRoute
  '/_authenticated/tasks/$graphId': typeof AuthenticatedTasksGraphIdRoute
  '/_authenticated/users/$username': typeof AuthenticatedUsersUsernameRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/_authenticated/ai-providers/': typeof AuthenticatedAiProvidersIndexRoute
  '/_authenticated/external-catalogs/': typeof AuthenticatedExternalCatalogsIndexRoute
  '/_authenticated/functions/': typeof AuthenticatedFunctionsIndexRoute
  '/_authenticated/ml-models/': typeof AuthenticatedMlModelsIndexRoute
  '/_authenticated/monitoring/': typeof AuthenticatedMonitoringIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/stages/': typeof AuthenticatedStagesIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/_authenticated/agents/semantic/builder': typeof AuthenticatedAgentsSemanticBuilderRoute
  '/_authenticated/agents/semantic/': typeof AuthenticatedAgentsSemanticIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio'
    | '/monitoring'
    | '/sign-in'
    | '/active-query'
    | '/database-explorer'
    | '/migration'
    | '/query-cost'
    | '/query-history'
    | '/agents/$agentId'
    | '/agents/skills'
    | '/agents/studio'
    | '/agents/tools'
    | '/monitoring/active'
    | '/monitoring/audit'
    | '/monitoring/cluster'
    | '/monitoring/health'
    | '/monitoring/loads'
    | '/monitoring/tasks'
    | '/roles/$name'
    | '/tasks/$graphId'
    | '/users/$username'
    | '/agents/'
    | '/ai-providers/'
    | '/external-catalogs/'
    | '/functions/'
    | '/ml-models/'
    | '/monitoring/'
    | '/roles/'
    | '/settings/'
    | '/stages/'
    | '/tasks/'
    | '/users/'
    | '/workspaces/'
    | '/agents/semantic/builder'
    | '/agents/semantic/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/studio'
    | '/sign-in'
    | '/active-query'
    | '/database-explorer'
    | '/migration'
    | '/query-cost'
    | '/query-history'
    | '/'
    | '/agents/$agentId'
    | '/agents/skills'
    | '/agents/studio'
    | '/agents/tools'
    | '/monitoring/active'
    | '/monitoring/audit'
    | '/monitoring/cluster'
    | '/monitoring/health'
    | '/monitoring/loads'
    | '/monitoring/tasks'
    | '/roles/$name'
    | '/tasks/$graphId'
    | '/users/$username'
    | '/agents'
    | '/ai-providers'
    | '/external-catalogs'
    | '/functions'
    | '/ml-models'
    | '/monitoring'
    | '/roles'
    | '/settings'
    | '/stages'
    | '/tasks'
    | '/users'
    | '/workspaces'
    | '/agents/semantic/builder'
    | '/agents/semantic'
  id:
    | '__root__'
    | '/_authenticated'
    | '/studio'
    | '/_authenticated/monitoring'
    | '/(auth)/sign-in'
    | '/_authenticated/active-query'
    | '/_authenticated/database-explorer'
    | '/_authenticated/migration'
    | '/_authenticated/query-cost'
    | '/_authenticated/query-history'
    | '/_authenticated/'
    | '/_authenticated/agents/$agentId'
    | '/_authenticated/agents/skills'
    | '/_authenticated/agents/studio'
    | '/_authenticated/agents/tools'
    | '/_authenticated/monitoring/active'
    | '/_authenticated/monitoring/audit'
    | '/_authenticated/monitoring/cluster'
    | '/_authenticated/monitoring/health'
    | '/_authenticated/monitoring/loads'
    | '/_authenticated/monitoring/tasks'
    | '/_authenticated/roles/$name'
    | '/_authenticated/tasks/$graphId'
    | '/_authenticated/users/$username'
    | '/_authenticated/agents/'
    | '/_authenticated/ai-providers/'
    | '/_authenticated/external-catalogs/'
    | '/_authenticated/functions/'
    | '/_authenticated/ml-models/'
    | '/_authenticated/monitoring/'
    | '/_authenticated/roles/'
    | '/_authenticated/settings/'
    | '/_authenticated/stages/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/workspaces/'
    | '/_authenticated/agents/semantic/builder'
    | '/_authenticated/agents/semantic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  StudioRoute: typeof StudioRoute
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/active-query': {
      id: '/_authenticated/active-query'
      path: '/active-query'
      fullPath: '/active-query'
      preLoaderRoute: typeof AuthenticatedActiveQueryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/database-explorer': {
      id: '/_authenticated/database-explorer'
      path: '/database-explorer'
      fullPath: '/database-explorer'
      preLoaderRoute: typeof AuthenticatedDatabaseExplorerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/migration': {
      id: '/_authenticated/migration'
      path: '/migration'
      fullPath: '/migration'
      preLoaderRoute: typeof AuthenticatedMigrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/query-cost': {
      id: '/_authenticated/query-cost'
      path: '/query-cost'
      fullPath: '/query-cost'
      preLoaderRoute: typeof AuthenticatedQueryCostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/query-history': {
      id: '/_authenticated/query-history'
      path: '/query-history'
      fullPath: '/query-history'
      preLoaderRoute: typeof AuthenticatedQueryHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/$agentId': {
      id: '/_authenticated/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/skills': {
      id: '/_authenticated/agents/skills'
      path: '/agents/skills'
      fullPath: '/agents/skills'
      preLoaderRoute: typeof AuthenticatedAgentsSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/studio': {
      id: '/_authenticated/agents/studio'
      path: '/agents/studio'
      fullPath: '/agents/studio'
      preLoaderRoute: typeof AuthenticatedAgentsStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/tools': {
      id: '/_authenticated/agents/tools'
      path: '/agents/tools'
      fullPath: '/agents/tools'
      preLoaderRoute: typeof AuthenticatedAgentsToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-providers/': {
      id: '/_authenticated/ai-providers/'
      path: '/ai-providers'
      fullPath: '/ai-providers/'
      preLoaderRoute: typeof AuthenticatedAiProvidersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/external-catalogs/': {
      id: '/_authenticated/external-catalogs/'
      path: '/external-catalogs'
      fullPath: '/external-catalogs/'
      preLoaderRoute: typeof AuthenticatedExternalCatalogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/functions/': {
      id: '/_authenticated/functions/'
      path: '/functions'
      fullPath: '/functions/'
      preLoaderRoute: typeof AuthenticatedFunctionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ml-models/': {
      id: '/_authenticated/ml-models/'
      path: '/ml-models'
      fullPath: '/ml-models/'
      preLoaderRoute: typeof AuthenticatedMlModelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring/': {
      id: '/_authenticated/monitoring/'
      path: '/'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof AuthenticatedMonitoringIndexRouteImport
      parentRoute: typeof AuthenticatedMonitoringRouteRoute
    }
    '/_authenticated/monitoring/active': {
      id: '/_authenticated/monitoring/active'
      path: '/active'
      fullPath: '/monitoring/active'
      preLoaderRoute: typeof AuthenticatedMonitoringActiveRouteImport
      parentRoute: typeof AuthenticatedMonitoringRouteRoute
    }
    '/_authenticated/monitoring/audit': {
      id: '/_authenticated/monitoring/audit'
      path: '/audit'
      fullPath: '/monitoring/audit'
      preLoaderRoute: typeof AuthenticatedMonitoringAuditRouteImport
      parentRoute: typeof AuthenticatedMonitoringRouteRoute
    }
    '/_authenticated/monitoring/cluster': {
      id: '/_authenticated/monitoring/cluster'
      path: '/cluster'
      fullPath: '/monitoring/cluster'
      preLoaderRoute: typeof AuthenticatedMonitoringClusterRouteImport
      parentRoute: typeof AuthenticatedMonitoringRouteRoute
    }
    '/_authenticated/monitoring/health': {
      id: '/_authenticated/monitoring/health'
      path: '/health'
      fullPath: '/monitoring/health'
      preLoaderRoute: typeof AuthenticatedMonitoringHealthRouteImport
      parentRoute: typeof AuthenticatedMonitoringRouteRoute
    }
    '/_authenticated/monitoring/loads': {
      id: '/_authenticated/monitoring/loads'
      path: '/loads'
      fullPath: '/monitoring/loads'
      preLoaderRoute: typeof AuthenticatedMonitoringLoadsRouteImport
      parentRoute: typeof AuthenticatedMonitoringRouteRoute
    }
    '/_authenticated/monitoring/tasks': {
      id: '/_authenticated/monitoring/tasks'
      path: '/tasks'
      fullPath: '/monitoring/tasks'
      preLoaderRoute: typeof AuthenticatedMonitoringTasksRouteImport
      parentRoute: typeof AuthenticatedMonitoringRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/$name': {
      id: '/_authenticated/roles/$name'
      path: '/roles/$name'
      fullPath: '/roles/$name'
      preLoaderRoute: typeof AuthenticatedRolesNameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stages/': {
      id: '/_authenticated/stages/'
      path: '/stages'
      fullPath: '/stages/'
      preLoaderRoute: typeof AuthenticatedStagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/$graphId': {
      id: '/_authenticated/tasks/$graphId'
      path: '/tasks/$graphId'
      fullPath: '/tasks/$graphId'
      preLoaderRoute: typeof AuthenticatedTasksGraphIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$username': {
      id: '/_authenticated/users/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof AuthenticatedUsersUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthenticatedWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/semantic/': {
      id: '/_authenticated/agents/semantic/'
      path: '/agents/semantic'
      fullPath: '/agents/semantic/'
      preLoaderRoute: typeof AuthenticatedAgentsSemanticIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/semantic/builder': {
      id: '/_authenticated/agents/semantic/builder'
      path: '/agents/semantic/builder'
      fullPath: '/agents/semantic/builder'
      preLoaderRoute: typeof AuthenticatedAgentsSemanticBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedMonitoringRouteRouteChildren {
  AuthenticatedMonitoringActiveRoute: typeof AuthenticatedMonitoringActiveRoute
  AuthenticatedMonitoringAuditRoute: typeof AuthenticatedMonitoringAuditRoute
  AuthenticatedMonitoringClusterRoute: typeof AuthenticatedMonitoringClusterRoute
  AuthenticatedMonitoringHealthRoute: typeof AuthenticatedMonitoringHealthRoute
  AuthenticatedMonitoringLoadsRoute: typeof AuthenticatedMonitoringLoadsRoute
  AuthenticatedMonitoringTasksRoute: typeof AuthenticatedMonitoringTasksRoute
  AuthenticatedMonitoringIndexRoute: typeof AuthenticatedMonitoringIndexRoute
}

const AuthenticatedMonitoringRouteRouteChildren: AuthenticatedMonitoringRouteRouteChildren =
  {
    AuthenticatedMonitoringActiveRoute: AuthenticatedMonitoringActiveRoute,
    AuthenticatedMonitoringAuditRoute: AuthenticatedMonitoringAuditRoute,
    AuthenticatedMonitoringClusterRoute: AuthenticatedMonitoringClusterRoute,
    AuthenticatedMonitoringHealthRoute: AuthenticatedMonitoringHealthRoute,
    AuthenticatedMonitoringLoadsRoute: AuthenticatedMonitoringLoadsRoute,
    AuthenticatedMonitoringTasksRoute: AuthenticatedMonitoringTasksRoute,
    AuthenticatedMonitoringIndexRoute: AuthenticatedMonitoringIndexRoute,
  }

const AuthenticatedMonitoringRouteRouteWithChildren =
  AuthenticatedMonitoringRouteRoute._addFileChildren(
    AuthenticatedMonitoringRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMonitoringRouteRoute: typeof AuthenticatedMonitoringRouteRouteWithChildren
  AuthenticatedActiveQueryRoute: typeof AuthenticatedActiveQueryRoute
  AuthenticatedDatabaseExplorerRoute: typeof AuthenticatedDatabaseExplorerRoute
  AuthenticatedMigrationRoute: typeof AuthenticatedMigrationRoute
  AuthenticatedQueryCostRoute: typeof AuthenticatedQueryCostRoute
  AuthenticatedQueryHistoryRoute: typeof AuthenticatedQueryHistoryRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
  AuthenticatedAgentsSkillsRoute: typeof AuthenticatedAgentsSkillsRoute
  AuthenticatedAgentsStudioRoute: typeof AuthenticatedAgentsStudioRoute
  AuthenticatedAgentsToolsRoute: typeof AuthenticatedAgentsToolsRoute
  AuthenticatedRolesNameRoute: typeof AuthenticatedRolesNameRoute
  AuthenticatedTasksGraphIdRoute: typeof AuthenticatedTasksGraphIdRoute
  AuthenticatedUsersUsernameRoute: typeof AuthenticatedUsersUsernameRoute
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
  AuthenticatedAiProvidersIndexRoute: typeof AuthenticatedAiProvidersIndexRoute
  AuthenticatedExternalCatalogsIndexRoute: typeof AuthenticatedExternalCatalogsIndexRoute
  AuthenticatedFunctionsIndexRoute: typeof AuthenticatedFunctionsIndexRoute
  AuthenticatedMlModelsIndexRoute: typeof AuthenticatedMlModelsIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedStagesIndexRoute: typeof AuthenticatedStagesIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWorkspacesIndexRoute: typeof AuthenticatedWorkspacesIndexRoute
  AuthenticatedAgentsSemanticBuilderRoute: typeof AuthenticatedAgentsSemanticBuilderRoute
  AuthenticatedAgentsSemanticIndexRoute: typeof AuthenticatedAgentsSemanticIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMonitoringRouteRoute:
    AuthenticatedMonitoringRouteRouteWithChildren,
  AuthenticatedActiveQueryRoute: AuthenticatedActiveQueryRoute,
  AuthenticatedDatabaseExplorerRoute: AuthenticatedDatabaseExplorerRoute,
  AuthenticatedMigrationRoute: AuthenticatedMigrationRoute,
  AuthenticatedQueryCostRoute: AuthenticatedQueryCostRoute,
  AuthenticatedQueryHistoryRoute: AuthenticatedQueryHistoryRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
  AuthenticatedAgentsSkillsRoute: AuthenticatedAgentsSkillsRoute,
  AuthenticatedAgentsStudioRoute: AuthenticatedAgentsStudioRoute,
  AuthenticatedAgentsToolsRoute: AuthenticatedAgentsToolsRoute,
  AuthenticatedRolesNameRoute: AuthenticatedRolesNameRoute,
  AuthenticatedTasksGraphIdRoute: AuthenticatedTasksGraphIdRoute,
  AuthenticatedUsersUsernameRoute: AuthenticatedUsersUsernameRoute,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
  AuthenticatedAiProvidersIndexRoute: AuthenticatedAiProvidersIndexRoute,
  AuthenticatedExternalCatalogsIndexRoute:
    AuthenticatedExternalCatalogsIndexRoute,
  AuthenticatedFunctionsIndexRoute: AuthenticatedFunctionsIndexRoute,
  AuthenticatedMlModelsIndexRoute: AuthenticatedMlModelsIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedStagesIndexRoute: AuthenticatedStagesIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWorkspacesIndexRoute: AuthenticatedWorkspacesIndexRoute,
  AuthenticatedAgentsSemanticBuilderRoute:
    AuthenticatedAgentsSemanticBuilderRoute,
  AuthenticatedAgentsSemanticIndexRoute: AuthenticatedAgentsSemanticIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  StudioRoute: StudioRoute,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
