from __future__ import annotations

from .contracts import Case
from .data_statements import data_statement_cases
from .geospatial import geospatial_data_cases


def core_cases(database: str) -> list[Case]:
    return data_statement_cases() + geospatial_data_cases() + [
        Case("query.literal", "query", "SELECT 42", [[42]], statement_rules=("queryStatement",)),
        Case(
            "query.unicode",
            "query",
            "SELECT 'Jakarta 🐘', 'a;b', '@not_a_stage'",
            [["Jakarta 🐘", "a;b", "@not_a_stage"]],
        ),
        Case("query.comment", "query", "SELECT /* @missing ; */ 1 -- @missing\n", [[1]]),
        Case("query.parameters", "query", "SELECT %s + %s", [[5]], parameters=(2, 3)),
        Case(
            "query.parameter_escaping",
            "query",
            "SELECT %s",
            [["O'Reilly; @missing 🐘"]],
            parameters=("O'Reilly; @missing 🐘",),
        ),
        Case(
            "query.filter",
            "query",
            "SELECT n FROM numbers WHERE n BETWEEN 2 AND 4 ORDER BY n",
            [[2], [3], [4]],
        ),
        Case(
            "query.aggregate",
            "query",
            "SELECT COUNT(*), SUM(n), AVG(n) FROM numbers",
            [[6, 15, 2.5]],
        ),
        Case(
            "query.cte",
            "query",
            "WITH x(k) AS (SELECT n FROM numbers WHERE n < 2) SELECT k FROM x ORDER BY k",
            [[0], [1]],
        ),
        Case(
            "query.join",
            "query",
            "SELECT a.n, b.n FROM numbers a JOIN numbers b ON a.n=b.n WHERE a.n=2",
            [[2, 2]],
        ),
        Case(
            "query.left_join",
            "query",
            "SELECT a.n, b.n FROM numbers a LEFT JOIN numbers b ON a.n=b.n AND b.n<1 WHERE a.n=2",
            [[2, None]],
        ),
        Case(
            "query.subquery",
            "query",
            "SELECT n FROM numbers WHERE n IN (SELECT n FROM numbers WHERE n=3)",
            [[3]],
        ),
        Case("query.union", "query", "SELECT 1 UNION SELECT 1", [[1]]),
        Case("query.intersect", "query", "SELECT 1 INTERSECT SELECT 1", [[1]]),
        Case("query.except", "query", "SELECT 1 EXCEPT SELECT 1", [], "empty"),
        Case(
            "query.order_limit",
            "query",
            "SELECT n FROM numbers ORDER BY n DESC LIMIT 2 OFFSET 1",
            [[4], [3]],
        ),
        Case(
            "query.window",
            "window",
            "SELECT n, ROW_NUMBER() OVER(ORDER BY n), "
            "LAG(n) OVER(ORDER BY n), LEAD(n) OVER(ORDER BY n) FROM numbers ORDER BY n",
            [
                [0, 1, None, 1],
                [1, 2, 0, 2],
                [2, 3, 1, 3],
                [3, 4, 2, 4],
                [4, 5, 3, 5],
                [5, 6, 4, None],
            ],
        ),
        Case(
            "query.window_frame",
            "window",
            "SELECT n, SUM(n) OVER (ORDER BY n ROWS BETWEEN "
            "1 PRECEDING AND CURRENT ROW) FROM numbers ORDER BY n",
            [[0, 0], [1, 1], [2, 3], [3, 5], [4, 7], [5, 9]],
        ),
        Case(
            "query.grouping_sets",
            "window",
            "SELECT n%2 AS k, COUNT(*) FROM numbers "
            "GROUP BY GROUPING SETS ((n%2), ()) ORDER BY k NULLS FIRST",
            [[None, 6], [0, 3], [1, 3]],
        ),
        Case("types.decimal", "types", "SELECT CAST('12.3400' AS DECIMAL(18,4))", [["12.3400"]]),
        Case("types.date", "types", "SELECT DATE '2024-02-29'", [["2024-02-29"]]),
        Case(
            "types.datetime",
            "types",
            "SELECT CAST('2024-02-29 12:34:56' AS DATETIME)",
            [["2024-02-29 12:34:56"]],
        ),
        Case(
            "types.time_duration",
            "types",
            "SELECT timediff('2024-01-03 03:04:05','2024-01-01 00:00:00'),"
            "timediff('2024-01-01 00:00:00','2024-01-02 01:02:03')",
            [[183845.0, -90123.0]],
        ),
        Case(
            "types.largeint",
            "types",
            "SELECT CAST('170141183460469231731687303715884105727' AS LARGEINT)",
            [["170141183460469231731687303715884105727"]],
        ),
        Case(
            "types.null",
            "types",
            "SELECT CAST(NULL AS INT), NULLIF(1,1), COALESCE(NULL,2)",
            [[None, None, 2]],
        ),
        Case("types.array", "types", "SELECT [1,2,3]", [1, 2, 3], "json"),
        Case("types.map", "types", "SELECT map{'a':1,'b':2}", {"a": 1, "b": 2}, "json"),
        Case(
            "types.struct",
            "types",
            "SELECT named_struct('a',1,'b','x')",
            {"a": 1, "b": "x"},
            "json",
        ),
        Case("types.json", "types", "SELECT parse_json('{\"a\":1}')", {"a": 1}, "json"),
        Case(
            "types.varbinary",
            "types",
            "SELECT CAST(unhex('00ff') AS VARBINARY)",
            [[{"hex": "00ff"}]],
        ),
        Case(
            "types.metadata",
            "types",
            "SELECT CAST(1 AS INT), CAST(1.25 AS DOUBLE), "
            "CAST(1.25 AS DECIMAL(10,2)), DATE '2024-01-02'",
            [3, 5, 246, 10],
            "column_types",
        ),
        Case(
            "types.null_metadata",
            "types",
            "SELECT CAST(NULL AS INT),CAST(NULL AS DECIMAL(10,2)),CAST(NULL AS DATE)",
            [3, 246, 10],
            "column_types",
        ),
        Case(
            "types.empty_metadata",
            "types",
            "SELECT CAST(n AS INT),CAST(n AS DECIMAL(10,2)) FROM numbers WHERE FALSE",
            [3, 246],
            "column_types",
        ),
        Case(
            "types.precision",
            "types",
            "SELECT CAST('99999999999999.9999' AS DECIMAL(18,4))",
            [["99999999999999.9999"]],
        ),
        Case("types.invalid_cast", "types", "SELECT CAST('not-a-number' AS INT)", [[None]]),
        Case(
            "session.variable",
            "session",
            "SELECT @value, '@value', 2+@number",
            [["abc", "@value", 5]],
            setup=("SET @value='abc'", "SET @number=3"),
            statement_rules=("setStatement",),
        ),
        Case(
            "session.variable_dollar",
            "session",
            "SELECT @value$sum",
            [[7]],
            setup=("SET @value$sum=7",),
        ),
        Case(
            "session.database",
            "session",
            "SELECT DATABASE()",
            [[database]],
            setup=(f"USE `{database}`",),
            statement_rules=("useDatabaseStatement",),
        ),
        Case(
            "session.timezone",
            "session",
            "SELECT @@time_zone",
            [["+07:00"]],
            setup=("SET time_zone='+07:00'",),
        ),
        Case(
            "session.system_timezone",
            "session",
            "SELECT @@time_zone",
            [["+07:00"]],
            setup=("SET @@session.time_zone='+07:00'",),
        ),
        Case(
            "session.missing_database",
            "session",
            "USE nova_sql_database_that_does_not_exist",
            error_code=1064,
            error_contains="Unknown database",
        ),
        Case(
            "session.reject_context_script",
            "session",
            f"SELECT 1; USE `{database}`; SELECT 2",
            error_code=1235,
        ),
        Case(
            "session.reject_role_script",
            "session",
            "SELECT 1; SET ROLE ACCOUNTADMIN",
            error_code=1235,
        ),
        Case(
            "session.reject_late_assignment",
            "session",
            "SELECT 1; SET @value=2",
            error_code=1235,
        ),
        Case(
            "session.prefix_assignment_script",
            "session",
            "SET @value=7; SELECT @value",
            [[7]],
        ),
        Case(
            "session.reject_transaction",
            "session",
            "BEGIN",
            error_code=1235,
            error_contains="not supported",
            statement_rules=("beginStatement",),
        ),
        Case(
            "session.reject_commit",
            "session",
            "COMMIT",
            error_code=1235,
            error_contains="not supported",
            statement_rules=("commitStatement",),
        ),
        Case(
            "session.reject_rollback",
            "session",
            "ROLLBACK",
            error_code=1235,
            error_contains="not supported",
            statement_rules=("rollbackStatement",),
        ),
        Case(
            "session.reject_autocommit_off",
            "session",
            "SET AUTOCOMMIT=0",
            error_code=1235,
            error_contains="not supported",
        ),
        Case(
            "session.reject_global",
            "session",
            "SET @@global.time_zone='+07:00'",
            error_code=1064,
            error_contains="not supported",
        ),
        Case(
            "session.role",
            "security",
            "SELECT CURRENT_ROLE()",
            [["ACCOUNTADMIN"]],
            setup=("SET ROLE ACCOUNTADMIN",),
            statement_rules=("setRoleStatement",),
        ),
        Case(
            "session.reject_role_all",
            "security",
            "SET ROLE ALL",
            error_code=1064,
            error_contains="one named role",
        ),
        Case(
            "session.reject_role_missing",
            "security",
            "SET ROLE nova_sql_unassigned_role",
            error_code=1045,
        ),
        Case("security.root_protected", "security", "DROP USER root", error_code=1064),
        Case(
            "security.accountadmin_protected",
            "security",
            "DROP ROLE ACCOUNTADMIN",
            error_code=1064,
            statement_rules=("dropRoleStatement",),
        ),
        Case(
            "security.function_protected",
            "security",
            "DROP GLOBAL FUNCTION AI_COMPLETE(STRING)",
            error_code=1064,
            statement_rules=("dropFunctionStatement",),
        ),
        Case(
            "session.prepared_rejected",
            "protocol",
            "PREPARE p FROM 'SELECT 1'",
            error_code=1235,
            error_contains="not supported",
            statement_rules=("prepareStatement",),
        ),
        Case("script.last_result", "protocol", "SELECT 1; SELECT 2", [[2]]),
        Case(
            "script.stop_on_error",
            "protocol",
            "SELECT * FROM missing_table; SELECT 2",
            error_code=1064,
        ),
        Case("query.syntax_error", "query", "SELECT FROM", error_code=1064),
        Case(
            "query.unknown_function",
            "query",
            "SELECT nova_sql_unknown_function(1)",
            error_code=1064,
        ),
        Case(
            "query.explain",
            "operations",
            "EXPLAIN SELECT SUM(n) FROM numbers",
            "TABLE: numbers",
            "contains",
        ),
        Case(
            "metadata.databases",
            "operations",
            f"SHOW DATABASES LIKE '{database}'",
            [[database]],
            statement_rules=("showDatabasesStatement",),
        ),
        Case(
            "metadata.tables",
            "operations",
            "SHOW TABLES LIKE 'numbers'",
            [["numbers"]],
            statement_rules=("showTableStatement",),
        ),
        Case(
            "metadata.describe",
            "operations",
            "DESCRIBE numbers",
            [["n", "int", "NO", "true", None, ""]],
            statement_rules=("descTableStatement",),
        ),
        Case(
            "metadata.show_create",
            "operations",
            "SHOW CREATE TABLE numbers",
            "DUPLICATE KEY",
            "contains",
            statement_rules=("showCreateTableStatement",),
        ),
        Case(
            "metadata.variables",
            "operations",
            "SHOW VARIABLES LIKE 'time_zone'",
            [["time_zone", "+07:00"]],
            setup=("SET time_zone='+07:00'",),
            statement_rules=("showVariablesStatement",),
        ),
        Case(
            "metadata.functions",
            "operations",
            "SHOW BUILTIN FUNCTIONS LIKE 'abs'",
            [["abs"]],
            statement_rules=("showFunctionsStatement",),
        ),
        Case(
            "ddl.ctas",
            "ddl",
            "SELECT COUNT(*) FROM ctas",
            [[6]],
            setup=("CREATE TABLE ctas PROPERTIES('replication_num'='1') AS SELECT * FROM numbers",),
            statement_rules=("createTableAsSelectStatement",),
        ),
        Case(
            "ddl.like",
            "ddl",
            "SELECT COUNT(*) FROM copied",
            [[0]],
            setup=("CREATE TABLE copied LIKE numbers",),
            statement_rules=("createTableLikeStatement",),
        ),
        Case(
            "ddl.view",
            "ddl",
            "SELECT n FROM sample_view ORDER BY n",
            [[0], [1]],
            setup=("CREATE VIEW sample_view AS SELECT n FROM numbers WHERE n<2",),
            statement_rules=("createViewStatement",),
        ),
        Case(
            "ddl.alter_view",
            "ddl",
            "SELECT n FROM altered_view",
            [[2]],
            setup=(
                "CREATE VIEW altered_view AS SELECT n FROM numbers WHERE n=1",
                "ALTER VIEW altered_view AS SELECT n FROM numbers WHERE n=2",
            ),
            statement_rules=("alterViewStatement",),
        ),
        Case(
            "ddl.destructive_refused",
            "ddl",
            "TRUNCATE TABLE numbers",
            error_code=1064,
            statement_rules=("truncateTableStatement",),
        ),
        Case(
            "ddl.drop_refused",
            "ddl",
            "DROP TABLE numbers",
            error_code=1064,
            statement_rules=("dropTableStatement",),
        ),
        Case(
            "stage.missing",
            "stage",
            "SELECT * FROM @nova_sql_absent_stage.data.csv",
            error_code=1064,
        ),
    ]
